---
name: Ansible Molecule

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  molecule:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - version_lt_1_0_0
          - latest
          - systemd
    steps:
      - name: Install Ansible Molecule.
        run: |
          pip3 install --user molecule molecule-plugins[podman] ansible-core~=2.18.7
          # `ansible-core~=2.18.7` is a workaround for https://github.com/ansible-community/molecule-plugins/issues/311

      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Run Ansible Molecule.
        run: |
          molecule --base-config molecule/base.yml test --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
