---
name: Ansible Molecule

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  molecule:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - version_lt_1_0_0
          - latest
          - systemd
    steps:
      - name: Create and activate virtual environment
        # Ansible Molecule won't run without this writable virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/venv" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/venv/bin" >> $GITHUB_PATH
    
      - name: Install Ansible Molecule.
        run: |
          pip3 install molecule molecule-plugins[podman] ansible-core 



      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Get Ansible Molecule version.
        run: |
          molecule --version

      - name: Run Ansible Molecule.
        run: |
          molecule --base-config molecule/base.yml test --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
